### ISSUE TITLE
Strange characters present in standalone taxonomy site when viewed from Windows

### ISSUE THREAD

**Issue by pslh** [gem/oq-platform-taxonomy#7]
When viewing the standalone taxonomy page for Adobe Blocks from a Windows browser (tried Chrome and Firefox).  I can see A-circumflex characters.

![screenshot 179](https://user-images.githubusercontent.com/1394902/43195057-40d3b06c-9004-11e8-8f03-a08f6a713316.png)

[http://localhost:8800/taxonomy/adobe-blocks--ado](http://localhost:8800/taxonomy/adobe-blocks--ado)

**Comment by daniviga** [comment]
This is both caused by garbage in the HTML code and the fact that the web server (Django) is started from a Windows CMD that does not provide a full UTF-8 encoding, but uses CP437 instead, so all `open()` are using such encoding.

For the same reason we had to https://github.com/gem/oq-engine/pull/3794 in the Engine it's sufficient to change https://github.com/gem/oq-platform-taxonomy/blob/master/openquakeplatform_taxonomy/views.py#L29 into 

```python
with open(cont_f, 'r', encoding='utf-8') as f:
```

having the `utf-8` encoding explicitly declared in the `open()` that reads the HTML dumps.

![screenshot from 2018-07-25 12-31-40](https://user-images.githubusercontent.com/1818657/43195921-bac12790-9006-11e8-9200-cd53a88a196a.png)
